//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreFrontEFSecured.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oddity
    {
        public int OddityID { get; set; }
        public string OddityName { get; set; }
        public int OriginID { get; set; }
        public Nullable<System.DateTime> RecoveryDate { get; set; }
        public decimal Price { get; set; }
        public int OddityStatusID { get; set; }
        public int GenreID { get; set; }
        public int UnitsSold { get; set; }
    
        public virtual Genre Genre { get; set; }
        public virtual OddityStatu OddityStatu { get; set; }
        public virtual Origin Origin { get; set; }
    }
}
